spring.application.name=ocs
server.port=${PORT:8066}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PSWD}
spring.jpa.hibernate.ddl-auto=update











